export const ACCOUNTS_CHANGE_PAGING = 'ACCOUNTS_CHANGE_PAGING';

export const ACCOUNTS_LOAD = 'ACCOUNTS_LOAD';
export const ACCOUNTS_LOAD_FAILED = 'ACCOUNTS_LOAD_FAILED';
export const ACCOUNTS_LOADED = 'ACCOUNTS_LOADED';

export const BLOCK_ACCOUNT_CONFIRM = 'BLOCK_ACCOUNT_CONFIRM';
export const BLOCK_ACCOUNT_UPDATE = 'BLOCK_ACCOUNT_UPDATE';
export const BLOCK_ACCOUNT_SUCCESS = 'BLOCK_ACCOUNT_SUCCESS';
export const BLOCK_ACCOUNT_END = 'BLOCK_ACCOUNT_END';
export const BLOCK_ACCOUNT_FAILED = 'BLOCK_ACCOUNT_FAILED';

export const EDIT_ACCOUNT_DIALOG = 'EDIT_ACCOUNT_DIALOG';
export const EDIT_ACCOUNT_UPDATE = 'EDIT_ACCOUNT_UPDATE';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT';
export const EDIT_ACCOUNT_END = 'EDIT_ACCOUNT_END';
export const EDIT_ACCOUNT_FAILED = 'EDIT_ACCOUNT_FAILED';

export const DELETE_ACCOUNT_CONFIRM = 'DELETE_ACCOUNT_CONFIRM';
export const DELETE_ACCOUNT_END = 'DELETE_ACCOUNT_END';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';
