export const SEC_SET_USER = 'SEC_SET_USER';
export const SEC_UNSET_USER = 'SEC_UNSET_USER';

export const SEC_SIGN_IN_REFRESH = 'SEC_SIGN_IN_REFRESH';
export const SEC_SIGN_IN_REFRESH_END = 'SEC_SIGN_IN_REFRESH_END';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_IN_END = 'SIGN_IN_END';

export const SIGN_UP_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const SIGN_UP_FAILED = 'REGISTER_ACCOUNT_FAILED';
